import React, { useState } from 'react';
import { AlertTriangle, Send, Check, Copy, ShieldAlert, Sparkles, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';

export interface IntelligentAlertData {
  fieldName: string;
  cropName: string;
  riskLevel: 'High' | 'Moderate' | 'Critical';
  ndviDropPct: number;
  ndwiDropPct: number;
  tempAnomalyCelsius: number;
  diseaseProbabilityPct: number;
  recommendedAction: string;
  zoneTarget?: string;
}

interface IntelligentAlertSystemProps {
  alert?: IntelligentAlertData;
  className?: string;
}

export function IntelligentAlertSystem({
  alert = {
    fieldName: 'Farm A',
    cropName: 'Tomato',
    riskLevel: 'High',
    ndviDropPct: 21,
    ndwiDropPct: 17,
    tempAnomalyCelsius: 3.4,
    diseaseProbabilityPct: 87,
    recommendedAction: 'Inspect Zone 3 within 24 hours.',
    zoneTarget: 'Zone 3',
  },
  className = '',
}: IntelligentAlertSystemProps) {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);
  const [isSendingTelegram, setIsSendingTelegram] = useState(false);
  const [telegramSent, setTelegramSent] = useState(false);

  const formattedAlertText = `🚨 EARLY WARNING ALERT
━━━━━━━━━━━━━━━━━━
🌾 Field: ${alert.fieldName}
🌱 Crop: ${alert.cropName}
⚠️ Risk Level: ${alert.riskLevel}

🔍 REASON:
• NDVI ↓ ${alert.ndviDropPct}%
• NDWI (Moisture) ↓ ${alert.ndwiDropPct}%
• Temperature Anomaly ↑ +${alert.tempAnomalyCelsius}°C
• Disease Probability: ${alert.diseaseProbabilityPct}%

💡 RECOMMENDED ACTION:
${alert.recommendedAction}
━━━━━━━━━━━━━━━━━━
🛰️ Generated by SkyCrop AI Agronomy Intelligence`;

  // 1. One-click share directly to Telegram app / web
  const handleOpenTelegram = () => {
    const encodedText = encodeURIComponent(formattedAlertText);
    const telegramUrl = `https://t.me/share/url?url=${encodeURIComponent('https://skycrop.farm')}&text=${encodedText}`;
    window.open(telegramUrl, '_blank', 'noopener,noreferrer');
    toast({
      title: 'Telegram Alert Launched',
      description: 'Opening Telegram to send the alert to your contacts or group.',
    });
  };

  // 2. Direct Bot dispatch to user's Telegram
  const handleDirectTelegramDispatch = async () => {
    setIsSendingTelegram(true);
    const botToken = (import.meta as any).env?.VITE_TELEGRAM_BOT_TOKEN || '8855692632:AAF22TKy3N1BEhG5X2JxR8ZGRHfJxmGxXDg';
    const chatId = (import.meta as any).env?.VITE_TELEGRAM_CHAT_ID || '8079572053';

    try {
      let dispatched = false;
      try {
        const backendRes = await fetch('http://localhost:8000/send-telegram-alert', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            chat_id: chatId,
            text: formattedAlertText,
          }),
        });
        if (backendRes.ok) {
          dispatched = true;
        }
      } catch {}

      if (!dispatched) {
        const res = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            chat_id: chatId,
            text: formattedAlertText,
          }),
        });

        const data = await res.json();
        if (!data.ok) {
          throw new Error(data.description || 'Telegram rejected message');
        }
      }

      setTelegramSent(true);
      toast({
        title: '✅ Alert Received on Telegram!',
        description: `Early warning message delivered directly to your Telegram chat.`,
      });
      setTimeout(() => setTelegramSent(false), 4000);
    } catch (err: any) {
      console.warn('Telegram Bot API dispatch error, opening app:', err);
      handleOpenTelegram();
    } finally {
      setIsSendingTelegram(false);
    }
  };

  const handleCopyAlert = async () => {
    try {
      await navigator.clipboard.writeText(formattedAlertText);
      setCopied(true);
      toast({
        title: 'Alert Copied',
        description: 'Formatted alert copied to clipboard.',
      });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({
        title: 'Copy Failed',
        variant: 'destructive',
      });
    }
  };

  return (
    <div
      className={`p-5 rounded-2xl bg-[#0c1422]/95 border border-rose-500/30 shadow-[0_0_30px_rgba(244,63,94,0.15)] backdrop-blur-xl text-gray-200 space-y-4 ${className}`}
    >
      {/* Top Header Badge */}
      <div className="flex items-center justify-between border-b border-white/10 pb-3">
        <div className="flex items-center gap-2">
          <span className="text-xl animate-pulse">🚨</span>
          <div>
            <h4 className="font-display font-extrabold text-base text-rose-400 tracking-wide">
              Early Warning
            </h4>
            <p className="text-[11px] text-gray-400 font-mono">
              Intelligent Actionable Advisory Engine
            </p>
          </div>
        </div>

        <span className="text-[10px] px-2.5 py-1 rounded-full bg-rose-500/20 text-rose-300 border border-rose-500/40 font-mono font-bold uppercase">
          {alert.riskLevel} Risk
        </span>
      </div>

      {/* Field Details */}
      <div className="space-y-1 text-xs font-mono">
        <div className="flex items-center gap-2">
          <span className="text-gray-400 w-16">Field:</span>
          <span className="font-bold text-white">{alert.fieldName}</span>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-gray-400 w-16">Crop:</span>
          <span className="font-bold text-white">{alert.cropName}</span>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-gray-400 w-16">Risk:</span>
          <span className="font-bold text-rose-400">{alert.riskLevel}</span>
        </div>
      </div>

      {/* Structured Reasons List */}
      <div className="space-y-2 pt-1">
        <span className="text-xs font-bold text-gray-300 font-mono uppercase tracking-wider block">
          Reason:
        </span>
        <ul className="space-y-1.5 text-xs font-mono text-gray-300 pl-1">
          <li className="flex items-center gap-2">
            <span className="text-rose-400 font-bold">•</span>
            <span>NDVI ↓ {alert.ndviDropPct}%</span>
          </li>
          <li className="flex items-center gap-2">
            <span className="text-rose-400 font-bold">•</span>
            <span>NDWI (Moisture) ↓ {alert.ndwiDropPct}%</span>
          </li>
          <li className="flex items-center gap-2">
            <span className="text-amber-400 font-bold">•</span>
            <span>Temperature anomaly ↑ (+{alert.tempAnomalyCelsius}°C)</span>
          </li>
          <li className="flex items-center gap-2">
            <span className="text-rose-400 font-bold">•</span>
            <span>Disease probability: {alert.diseaseProbabilityPct}%</span>
          </li>
        </ul>
      </div>

      {/* Recommended Action */}
      <div className="p-3 rounded-xl bg-black/50 border border-white/10 space-y-1">
        <span className="text-[10px] font-bold text-emerald-400 font-mono uppercase tracking-wider block">
          Recommended action:
        </span>
        <p className="text-xs font-bold text-white font-mono">
          {alert.recommendedAction}
        </p>
      </div>

      {/* Telegram Action Bar */}
      <div className="pt-2 border-t border-white/10 flex flex-wrap items-center gap-2">
        <Button
          onClick={handleOpenTelegram}
          className="flex-1 h-9 text-xs font-bold bg-[#229ED9] hover:bg-[#1E88E5] text-white shadow-[0_0_15px_rgba(34,158,217,0.4)] rounded-xl flex items-center justify-center gap-2"
        >
          <Send className="w-3.5 h-3.5" />
          Send Alert via Telegram
        </Button>

        <Button
          variant="outline"
          size="sm"
          onClick={handleDirectTelegramDispatch}
          disabled={isSendingTelegram}
          className="h-9 text-xs font-semibold border-white/20 hover:bg-white/10 rounded-xl"
          title="Instant Telegram Bot Dispatch"
        >
          {telegramSent ? (
            <span className="text-emerald-400 flex items-center gap-1 font-bold">
              <Check className="w-3.5 h-3.5" /> Dispatched
            </span>
          ) : isSendingTelegram ? (
            'Dispatching...'
          ) : (
            'Telegram Bot'
          )}
        </Button>

        <Button
          variant="ghost"
          size="icon"
          onClick={handleCopyAlert}
          className="h-9 w-9 rounded-xl text-gray-400 hover:text-white hover:bg-white/10"
          title="Copy Alert Text"
        >
          {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
        </Button>
      </div>
    </div>
  );
}
