import { useState } from 'react';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Printer, Share2, FileText, CheckCircle2, AlertTriangle, ShieldCheck, Leaf, Calendar, Stethoscope, Droplets, Pill, Sparkles, Clock, AlertCircle } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { TreatmentProtocol } from '@/lib/cropDiseaseData';

export interface PrescriptionData {
  plantName: string;
  diseaseName: string;
  scientificName?: string;
  healthStatus: string;
  severity: string;
  confidence: string;
  treatment?: TreatmentProtocol;
  recommendations: string[];
  preventiveMeasures: string[];
  imagePreview?: string | null;
  farmerName?: string;
  fieldName?: string;
}

interface PrescriptionModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: PrescriptionData | null;
}

export function PrescriptionModal({ isOpen, onClose, data }: PrescriptionModalProps) {
  const { toast } = useToast();
  const [isPrinting, setIsPrinting] = useState(false);

  if (!data) return null;

  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const prescriptionId = `RX-CROP-${Math.floor(100000 + Math.random() * 900000)}`;

  const handlePrint = () => {
    setIsPrinting(true);
    setTimeout(() => {
      window.print();
      setIsPrinting(false);
      toast({
        title: 'Prescription Ready',
        description: 'Sent to printer / PDF export dialog.',
      });
    }, 200);
  };

  const handleWhatsAppShare = () => {
    const text = `🌿 *SKY CROP HEALTH - DIGITAL PRESCRIPTION* 🌿\n\n` +
      `📋 *Prescription ID:* ${prescriptionId}\n` +
      `📅 *Date:* ${currentDate}\n` +
      `🌱 *Crop:* ${data.plantName}\n` +
      `🔬 *Diagnosis:* ${data.diseaseName} ${data.scientificName ? `(${data.scientificName})` : ''}\n` +
      `⚠️ *Severity:* ${data.severity} Risk (AI Match: ${data.confidence})\n\n` +
      (data.treatment ? 
        `💊 *CHEMICAL DOSAGE:*\n• ${data.treatment.chemicalName}\n• Dosage: ${data.treatment.dosage}\n• Timing: ${data.treatment.sprayInterval}\n\n` +
        `🌿 *ORGANIC ALTERNATIVE:*\n• ${data.treatment.organicOption} (${data.treatment.organicDosage})\n\n` +
        `🚨 *IMMEDIATE ACTION:*\n• ${data.treatment.immediateAction}\n\n`
        : '') +
      `📋 *RECOMMENDATIONS:*\n` +
      data.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n') +
      `\n\n🛡️ *PREVENTION:*\n` +
      data.preventiveMeasures.slice(0, 3).map((p, i) => `• ${p}`).join('\n') +
      `\n\n_Generated by Sky Crop Health AI Agronomist._`;

    const url = `https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[92vh] overflow-y-auto p-0 border-primary/20 bg-background/95 backdrop-blur-xl shadow-2xl">
        {/* Printable Area */}
        <div id="crop-prescription-print" className="p-6 md:p-8 space-y-6">
          {/* Header Banner */}
          <div className="flex items-start justify-between border-b pb-4 border-border/60">
            <div>
              <div className="flex items-center gap-3 mb-1">
                <div className="bg-primary/20 p-2.5 rounded-xl text-primary shadow-sm">
                  <Stethoscope className="w-6 h-6" />
                </div>
                <div>
                  <h2 className="text-2xl font-bold font-display tracking-tight text-foreground">
                    SKY CROP HEALTH
                  </h2>
                  <p className="text-xs text-muted-foreground font-medium">
                    AI Precision Plant Pathology & Agronomic Prescription Studio
                  </p>
                </div>
              </div>
            </div>

            <div className="text-right">
              <span className="text-xs font-mono bg-primary/10 text-primary font-bold px-3 py-1 rounded-full border border-primary/20">
                {prescriptionId}
              </span>
              <div className="flex items-center justify-end gap-1.5 text-xs text-muted-foreground mt-2">
                <Calendar className="w-3.5 h-3.5" />
                {currentDate}
              </div>
            </div>
          </div>

          {/* Plant & Diagnosis Info Card */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 bg-secondary/30 p-4 rounded-xl border border-border/50">
            <div>
              <p className="text-xs text-muted-foreground uppercase font-bold tracking-wider">Crop Species</p>
              <p className="text-lg font-bold text-foreground mt-0.5 flex items-center gap-1.5">
                <Leaf className="w-4 h-4 text-primary" /> {data.plantName}
              </p>
            </div>

            <div>
              <p className="text-xs text-muted-foreground uppercase font-bold tracking-wider">Pathology Diagnosis</p>
              <p className={`text-base font-bold mt-0.5 ${data.healthStatus === 'Healthy' ? 'text-green-500' : 'text-destructive'}`}>
                {data.diseaseName}
              </p>
              {data.scientificName && (
                <p className="text-xs italic text-muted-foreground">({data.scientificName})</p>
              )}
            </div>

            <div>
              <p className="text-xs text-muted-foreground uppercase font-bold tracking-wider">Severity & Confidence</p>
              <div className="flex items-center gap-2 mt-1">
                <Badge variant={data.severity === 'High' ? 'destructive' : (data.severity === 'Medium' ? 'secondary' : 'default')} className="text-xs font-semibold">
                  {data.severity} Risk
                </Badge>
                <span className="text-xs font-bold text-primary bg-primary/10 px-2 py-0.5 rounded-full border border-primary/20">
                  {data.confidence} Match
                </span>
              </div>
            </div>
          </div>

          {/* Detailed Treatment Protocol */}
          {data.treatment && data.healthStatus !== 'Healthy' && (
            <div className="space-y-3">
              <div className="flex items-center gap-2 text-primary font-bold text-sm border-b border-primary/20 pb-1.5">
                <Pill className="w-4 h-4 text-primary" />
                <span>Rx: Exact Treatment Protocols & Dosages</span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
                {/* Chemical Treatment Box */}
                <div className="bg-primary/5 border border-primary/20 rounded-xl p-4 space-y-2">
                  <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-primary">
                    <Droplets className="w-3.5 h-3.5" /> Chemical Fungicide / Bactericide
                  </div>
                  <p className="text-sm font-bold text-foreground">{data.treatment.chemicalName}</p>
                  <div className="text-xs bg-background/80 p-2 rounded-lg border border-primary/10 space-y-1">
                    <p><strong className="text-primary">Exact Dosage:</strong> {data.treatment.dosage}</p>
                    <p className="text-muted-foreground flex items-center gap-1">
                      <Clock className="w-3 h-3 text-muted-foreground" /> {data.treatment.sprayInterval}
                    </p>
                  </div>
                </div>

                {/* Organic / Bio Treatment Box */}
                <div className="bg-green-500/5 border border-green-500/20 rounded-xl p-4 space-y-2">
                  <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-green-500">
                    <Sparkles className="w-3.5 h-3.5" /> Organic & Biological Alternative
                  </div>
                  <p className="text-sm font-bold text-foreground">{data.treatment.organicOption}</p>
                  <div className="text-xs bg-background/80 p-2 rounded-lg border border-green-500/10 space-y-1">
                    <p><strong className="text-green-500">Organic Dosage:</strong> {data.treatment.organicDosage}</p>
                    <p className="text-muted-foreground">Eco-friendly & pollinator safe</p>
                  </div>
                </div>
              </div>

              {/* Immediate Field Action */}
              {data.treatment.immediateAction && (
                <div className="bg-destructive/5 border border-destructive/20 rounded-xl p-3.5 flex items-start gap-3 text-xs">
                  <AlertCircle className="w-4 h-4 text-destructive shrink-0 mt-0.5" />
                  <div>
                    <strong className="text-destructive font-semibold">Immediate Emergency Action:</strong>
                    <p className="text-foreground/90 mt-0.5 leading-relaxed">{data.treatment.immediateAction}</p>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Full Step-by-Step Recommendations */}
          <div className="space-y-2.5">
            <div className="flex items-center gap-2 text-foreground font-bold text-xs uppercase tracking-wider">
              <CheckCircle2 className="w-4 h-4 text-primary" />
              <span>Agronomic Cure & Field Management Schedule</span>
            </div>

            <div className="bg-secondary/20 border border-border/60 rounded-xl p-4 space-y-2">
              {data.recommendations.map((rec, idx) => (
                <div key={idx} className="flex items-start gap-2.5 text-xs text-foreground/90">
                  <span className="bg-primary/20 text-primary font-bold text-[10px] rounded-full w-4 h-4 flex items-center justify-center shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <p className="leading-relaxed">{rec}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Preventive Measures */}
          {data.preventiveMeasures && data.preventiveMeasures.length > 0 && (
            <div className="space-y-2.5">
              <div className="flex items-center gap-2 text-muted-foreground font-bold text-xs uppercase tracking-wider">
                <ShieldCheck className="w-4 h-4 text-blue-400" />
                <span>Field Sanitation & Future Prevention Protocols</span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-xs">
                {data.preventiveMeasures.map((measure, idx) => (
                  <div key={idx} className="flex items-start gap-2 bg-secondary/20 p-2.5 rounded-lg border border-border/40">
                    <CheckCircle2 className="w-3.5 h-3.5 text-blue-400 shrink-0 mt-0.5" />
                    <span className="leading-relaxed">{measure}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Footer Notice */}
          <div className="text-[11px] text-muted-foreground/80 border-t border-border/40 pt-3 flex flex-col sm:flex-row items-center justify-between gap-1">
            <p>Certified by Sky Crop Health AI Diagnostic Model (MobileNetV3 / ResNet)</p>
            <p>Always verify local weather conditions before foliar spraying.</p>
          </div>
        </div>

        {/* Modal Actions */}
        <div className="flex items-center justify-between p-4 bg-secondary/40 border-t border-border/50">
          <Button variant="outline" size="sm" onClick={onClose}>
            Close
          </Button>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              className="gap-1.5 text-green-500 border-green-500/30 hover:bg-green-500/10 font-semibold"
              onClick={handleWhatsAppShare}
            >
              <Share2 className="w-4 h-4" /> Share on WhatsApp
            </Button>

            <Button size="sm" className="gap-1.5 font-semibold" onClick={handlePrint} disabled={isPrinting}>
              <Printer className="w-4 h-4" /> Print / Save PDF
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
